---
- name: Play settings
  hosts: all
  become: true

  vars:
    someuser: "{{ ev_user }}"

  tasks:
    - name: ensure .ssh dir
      file:
        state: directory
        path: "/home/{{ someuser }}/.ssh"
        mode: 0700
        owner: "{{ someuser }}"
        group: "{{ someuser }}"

    - name: set authorized key
      authorized_key:
        user: "{{ someuser }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      register: authkey

    - name: print
      debug:
        msg: "{{ authkey.keyfile }}"
