---
- name: Play
  hosts: all
  become: true

  vars:
    someuser: "{{ ev_user }}"

  tasks:
  - name: ensure sudo user file
    copy:
      dest: "/etc/sudoers.d/{{ someuser }}"
      content: "{{ someuser }} ALL=(ALL) NOPASSWD: ALL"
    register: sudouserfile
  - name: print
    debug:
      var: sudouserfile

  - name: disable NOPASSWD for %wheel
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel\s'
      line: '%wheel ALL=(ALL) PASSWD: ALL'
    when: sudouserfile.changed

