---
- hosts: rhel8nodes
  become: true
  gather_facts: false

  vars:
    ipinfo: {}
    outputdir: /home/hennie/ansible/tmp

  tasks:

    - name: define today date
      command: date '+%Y-%m-%d'
      register: todaydate
      delegate_to: localhost

    - name: create output dir
      file:
        path: "{{ outputdir }}/{{ todaydate.stdout }}/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost

    - name: get ip a
      command: ip a
      register: collectip

    - name: put ip a output in dictionary
      set_fact:
        #ipinfo: "{{ ipinfo|combine({'ip a': {'status': 'UNKNOWN', 'message' : collectip.stdout_lines }}, recursive=True) }}"
        ipinfo: "{{ ipinfo|combine({'ip a': {'message' : collectip.stdout_lines }}, recursive=True) }}"

    - name: get ip r
      command: ip r
      register: collectroute

    - name: put ip r output in dictionary
      set_fact:
        #ipinfo: "{{ ipinfo|combine({'ip a': {'status': 'UNKNOWN', 'message' : collectroute.stdout_lines }}, recursive=True) }}"
        ipinfo: "{{ ipinfo|combine({'ip r': {'message' : collectroute.stdout_lines }}, recursive=True) }}"

    - name: put ip dictionary in file
      copy:
        content: "{{ ipinfo | to_nice_yaml }}"
        dest: "{{ outputdir }}/{{ todaydate.stdout }}/{{ inventory_hostname }}/ipinfo"
      delegate_to: localhost

    - name: get fstab
      copy:
        src: /etc/fstab
        dest: "{{ outputdir }}/{{ todaydate.stdout }}/{{ inventory_hostname }}/"

    #- name: get lvs.cf
      #copy:
        #src: /etc/sysconfig/ha/lvs.cf
        #dest: "{{ outputdir }}/{{ todaydate.stdout }}/{{ inventory_hostname }}/"
      #when: inventory_hostname in groups.loadbalancers

    #- name: get httpd confs
      #copy:
        #src: /etc/httpd/conf/vhosts/
        #dest: "{{ outputdir }}/{{ todaydate.stdout }}/{{ inventory_hostname }}/"
      #when: inventory_hostname in groups.reverseproxies


...

