---
- hosts: node1

  tasks:
    - name: update your system
      block:
      - name: update YUM
        yum:
          name: '*'
          state: latest
      - name: disable firewalld
        service:
          name: firewalld
          state: stopped
          enabled: no
        register: selinuxpermissive
      - name: reboot
        reboot:
        when: selinuxpermissive.changed
      tags: update_node

    - name: SELinux permissive
      block:
      - name: set SELinux in permissive mode
        command: setenforce 0
      - name: set permissive in sysconfig
        lineinfile:
          path: /etc/sysconfig/selinux
          regexp: "^SELINUX=enforcing"
          line: SELINUX=permissive
      tags: selinux_permissive
  
    - name: Install K3s
      block:
      - name: download K3s
        get_url:
          url: https://get.k3s.io
          mode: 0700
          dest: /root/k3s.sh
      - name: run this install script
        shell: /root/k3s.sh
      - name: mod k3s yaml file
        file:
          path: /etc/rancher/k3s/k3s.yaml
          mode: 0644
      tags: selinux_permissive

    - name: deploy AWX operaton on Kubernetes
      block:
      - name: install rpms
        yum:
          state: present
          name: "{{ item }}"
        loop:
          - git
          - make

      - name: clone operator deployment code
        git:
          repo: https://github.com/ansible/awx-operator.git
          dest: /root/awx-operator
      - name: create namespace
        shell: |
          /usr/local/bin/kubectl create ns awx
          /usr/local/bin/kubectl config set-context --current --namespace=awx
          cd /root/awx-operator
          yum -y install jq
          RELEASE_TAG=`curl -s https://api.github.com/repos/ansible/awx-operator/releases/latest | grep tag_name | cut -d '"' -f 4`
          git checkout $RELEASE_TAG 
          export NAMESPACE=awx
          export PATH=$PATH:/usr/local/bin
          make deploy
        ignore_errors: true

      - name: install AWX on centos8
        block:
          - name: create public-static-pvc.yaml
            copy:
              dest: /root/public-static-pvc.yaml
              content: |
                ---
                apiVersion: v1
                kind: PersistentVolumeClaim
                metadata:
                  name: public-static-data-pvc
                spec:
                  accessModes:
                    - ReadWriteOnce
                  storageClassName: local-path
                  resources:
                    requests:
                      storage: 5Gi

          - name: apply
            command: /usr/local/bin/kubectl apply -f /root/public-static-pvc.yaml -n awx

          - name: create deployment file
            copy:
              dest: /root/awx-instance-deployment.yml
              content: |
                ---
                apiVersion: awx.ansible.com/v1beta1
                kind: AWX
                metadata:
                  name: awx
                spec:
                  service_type: nodeport
                  projects_persistence: true
                  projects_storage_access_mode: ReadWriteOnce
                  web_extra_volume_mounts: |
                    - name: static-data
                      mountPath: /var/lib/awx/public
                  extra_volumes: |
                    - name: static-data
                      persistentVolumeClaim:
                        claimName: public-static-data-pvc

          - name: now install AWX
            command: /usr/local/bin/kubectl apply -f /root/awx-instance-deployment.yml -n awx

