---
- hosts: rhel8-node3
  gather_facts: true
  become: true

  vars:
    DBPassword: xae3Aiphuch7
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: install Zabbix repository
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: cleanup
      command: yum clean all

    - name: install Zabbix server,frontend,agent
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-server-pgsql
        - zabbix-web-pgsql
        - zabbix-nginx-conf
        - zabbix-sql-scripts
        - zabbix-selinux-policy
        - zabbix-agent
        - zabbix-web-service
        - postgresql
        - postgresql-server
        - nginx
        - php-fpm
        - python3-psycopg2

    - name: initialize postgresql
      command: /usr/bin/postgresql-setup --initdb
      ignore_errors: true

    - name: ensure postgresql running
      service:
        name: postgresql
        state: started
        enabled: yes
    - name: create database user
      postgresql_user:
        state: present
        name: zabbix
        password: "{{ DBPassword }}"
      become: true
      become_user: postgres
      tags: createdbuser
    - name: create initial database
      postgresql_db:
        name: zabbix
      become: true
      become_user: postgres
      tags: createdb

    - name: import initial schema and data
      shell: |
        set -o pipefail
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: configure database passwd
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        state: present
        insertafter: '^# DBPassword='
        line: "DBPassword={{ DBPassword }}"
      tags: setdbpassword

    - name: configure PHP zabbix frontend listen
      lineinfile:
        path: /etc/nginx/conf.d/zabbix.conf
        state: present
        insertafter: '#        listen          8080;'
        line: '        listen          8080;'
      tags: listen
    - name: configure PHP zabbix frontend servername
      lineinfile:
        path: /etc/nginx/conf.d/zabbix.conf
        state: present
        insertafter: '#        server_name     example.com;'
        line: "        server_name          {{ ansible_fqdn }};"
      tags: server_name

    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - zabbix-web-service
        - nginx
        - php-fpm
      tags: startservices

    - name: open firewall
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
      tags: firewall

    - name: set link for zabbix webfrontend
      file:
        src: /usr/share/zabbix
        dest: /usr/share/nginx/html
        state: link

    - name: fix php.ini
      block:
      - name: post_max_size
        lineinfile:
          path: /etc/php.ini
          regexp: '^post_max_size'
          line: 'post_max_size = 16M'
      - name: max_execution_time
        lineinfile:
          path: /etc/php.ini
          regexp: '^max_execution_time'
          line: 'max_execution_time = 300'
      - name: max_input_time
        lineinfile:
          path: /etc/php.ini
          regexp: '^max_input_time'
          line: 'max_input_time = 300'
      tags: phpini
     
    


         

...
