---
- hosts: gitlabrunner
  become: true
  gather_facts: false

  vars: []

  tasks:
    - name: get the RPM from this dir
      copy:
        #src: ./gitlab-runner_amd64.rpm
	#curl -LJO "https://gitlab-runner-downloads.s3.amazonaws.com/latest/rpm/gitlab-runner_amd64.rpm"
        dest: /tmp/gitlab-runner_amd64.rpm

    - name: install the rpm
      yum:
        name: /tmp/gitlab-runner_amd64.rpm
        state: present

    - name: remove the rpm
      file:
        path: /tmp/gitlab-runner_amd64.rpm
        state: absent

    - name: install podman
      dnf:
        name: "{{ item }}"
      loop:
        - podman
        - podman-docker

...
