---
- hosts: gitlabserver
  become: true
  gather_facts: true

  vars: []

  tasks:
  - name: install dependencies
    dnf:
      state: present
      name: "{{ item }}"
    loop:
      - policycoreutils
      - openssh-server
      - perl

  - name: ensure SSHD running
    service:
      name: sshd
      state: started
      enabled: true

  - name: check and enable firewalld
    service:
      name: firewalld
      state: started
      enabled: true

  - name: enable http/https in firewall
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - http
      - https
    tags: firewalld

  - name: set time
    command: chronyc -a makestep

  - name: install postfix
    dnf:
      name: postfix
      state: present

  - name: ensure postfix running
    service:
      name: postfix
      state: started
      enabled: true
    ignore_errors: true

  - name: get and install gitlab repo script
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
      dest: /root
      mode: 0400

  - name: install it
    command:
      sudo bash /root/script.rpm.sh

  - name: install gitlab-ee
    shell:
      sudo EXTERNAL_URL="https://$(hostname -f)" dnf install -y gitlab-ce

  - name: fetch initial root password
    fetch:
      src: /etc/gitlab/initial_root_password
      dest: "initialrootpassword_gitlab_{{ inventory_hostname }}"
      flat: true
    tags: fetchRootPW

...
