---
- hosts: crdlxhv01

  tasks:
    - name: update 
      yum:
        name: '*'
        state: latest

    - name: install podman
      yum:
        name: podman
        state: present

    - name: install kvm hypervisor
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - '@virt'
        - libguestfs-tools
        - virt-manager

    - name: ensure sock group is set
      lineinfile:
        regexp: '^unix_sock_group'
        line: 'unix_sock_group = "libvirt"'
    - name: ensure sock rw is set
      lineinfile:
        regexp: '^unix_sock_rw_perms'
        line: 'unix_sock_rw_perms = "0770"'

    - name: ensure passwordless sudo for group libvirt
      copy:
        dest: /etc/sudoers.d/libvirt
        content: |
          %libvirt ALL=(ALL) NOPASSWD: ALL

    - name: start and enable libvirtd
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: download kubectl
      shell: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

    - name: copy to usrlocalbin
      shell: |
        cp /root/kubectl /usr/local/bin
    - name: set properties
      command: chmod +x /usr/local/bin/kubectl

    - name: install minikube
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

    - name: copy to usrlocalbin
      shell: |
        cp /root/minikube /usr/local/bin
    - name: set properties
      command: chmod +x /usr/local/bin/kubectl

    - name: disable swap
      command: swapoff -a
    - name: disable swap fstab
      shell: |
        sed -i '/swap/ s/^/#/' /etc/fstab

