---
- hosts: rhel8-master
  become: true
  gather_facts: true

  tasks:
  - name: add centos8-master /etc/hosts
    lineinfile:
      path: /etc/hosts
      state: present
      regexp: '^(192.168.121.*)centos8(.*master)$'
      line: '192.168.121.92 centos8-master master'

  - name: install pgsql repo
    dnf:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present
      validate_certs: no
      disable_gpg_check: yes

  - name: disable rhel8 pgsql module 
    command: "sudo dnf -qy module disable postgresql"

  - name: install pgsql13
    dnf:
      name: postgresql13-server
      state: present
      validate_certs: no
      disable_gpg_check: yes

  - name: initialize pgsql13
    command: sudo /usr/pgsql-13/bin/postgresql-13-setup initdb

  - name: start and enable postgresql-13 service
    service:
      name: postgresql-13
      state: started
      enabled: yes
